import chalk from 'chalk';
import path from 'path';
import { getCurrentVersion, loadConfig, readConfigVersion, saveConfig, type UniKitConfig } from '../../core/config.js';
import {
  buildManagedSkillsState, getAvailableSkills, updateSkills,
  type SkillUpdateEntry,
} from '../../core/installer/skills.js';
import {
  buildManagedSubagentsState, updateSubagents,
  type SubagentUpdateEntry,
} from '../../core/installer/subagents.js';
import { installEngineTemplates, installCliContract, installGateResultContract, installDevPrinciples, installEngineMcpRules, readDeliveredEngineMcpServer, installGamedesignSystemAssets, installGenreProfiles, installModulesYml } from '../../core/installer/system-assets.js';
import { injectMcpRules } from '../../core/installer/mcp-injection.js';
import { installExtensionSkills, installExtensionSubagents } from '../../core/installer/extensions.js';
import { syncAllModules } from '../../core/installer/rules-sync.js';
import { runProjectMemoryMigrations } from '../../core/memory-migrations/index.js';
import { renderSyncRulesEvents } from './rules.js';
import { discoverMcpServers, collectMcpRules } from '../../core/mcp.js';
import { resolveSelectedEngineServer } from '../../core/mcp-rules.js';
import { swapMcpRecheckNotes } from '../../core/installer/mcp-notes.js';
import { getAgentConfig } from '../../core/agents.js';
import { fileExists } from '../../utils/fs.js';
import { collectReplacedSkills, refreshExtensions } from '../../core/extension-ops.js';
import { loadExtensionManifest, getExtensionDir } from '../../core/extensions.js';
import { createRegistry, type ChainedRegistry } from '../../core/registry/index.js';
import { bootstrapModuleRules } from '../../core/installer/rules-bootstrap.js';
import { resolveModuleCatalog, type ModuleCatalog } from '../../core/installer/module-catalog.js';
import { listModules, resolveSkillModule, moduleHasInstalledSkills } from '../../core/modules.js';
import { logInfo, logWarn } from '../../utils/log.js';
import { applyAllInjections } from '../../core/injections.js';

interface UpdateCommandOptions {
  force?: boolean;
  installNew?: boolean;
  skipNew?: boolean;
}

function formatReason(reason: string): string {
  switch (reason) {
    case 'source-hash-changed':
      return 'source changed';
    case 'installed-hash-drift':
      return 'local drift';
    case 'missing-managed-state':
      return 'state missing';
    case 'missing-installed-artifact':
      return 'artifact missing';
    case 'package-removed':
      return 'removed from package';
    case 'new-skill-not-installed':
      return 'new in package';
    case 'new-skill-installed':
      return 'new skill installed';
    case 'force-clean-reinstall':
      return 'force reinstall';
    case 'install-failed':
      return 'install failed';
    case 'source-missing':
      return 'source unavailable';
    case 'replaced-by-extension':
      return 'replaced by extension';
    default:
      return reason;
  }
}

function groupEntriesByStatus(entries: SkillUpdateEntry[]): Record<'changed' | 'unchanged' | 'skipped' | 'removed' | 'replaced', SkillUpdateEntry[]> {
  return {
    changed: entries.filter(entry => entry.status === 'changed').sort((a, b) => a.skill.localeCompare(b.skill)),
    unchanged: entries.filter(entry => entry.status === 'unchanged').sort((a, b) => a.skill.localeCompare(b.skill)),
    skipped: entries.filter(entry => entry.status === 'skipped').sort((a, b) => a.skill.localeCompare(b.skill)),
    removed: entries.filter(entry => entry.status === 'removed').sort((a, b) => a.skill.localeCompare(b.skill)),
    replaced: entries.filter(entry => entry.status === 'replaced').sort((a, b) => a.skill.localeCompare(b.skill)),
  };
}

/**
 * Bootstrap rules for modules that received their FIRST skill in this update run
 * (`update --install-new` / the interactive new-skill prompt). The invariant is
 * bootstrap = f(installed skills): a project that just opted into a new module's
 * skills must also receive that module's rules, which the Phase 2 sync that
 * follows cannot deliver (it only carries already-installed rules).
 *
 * EXIT-FREE: catalogs are resolved here and unreachable / engine-missing ones
 * are soft-skipped (a flaky or code-only registry must not abort the update).
 * config mutations are persisted by updateCommand's own saveConfig and the
 * index is regenerated by syncAllModules Phase 3 — neither happens here.
 */
async function bootstrapNewSkillModuleRules(
  projectDir: string,
  config: UniKitConfig,
  registry: ChainedRegistry,
  engineId: string,
  installNewSkills: Set<string>,
): Promise<void> {
  if (installNewSkills.size === 0) {
    return;
  }

  const newSkillList = [...installNewSkills];
  const targetModules = listModules().filter(module =>
    newSkillList.some(s => resolveSkillModule(s)?.id === module.id)
    && moduleHasInstalledSkills(config, module),
  );
  if (targetModules.length === 0) {
    return;
  }

  // Resolve catalogs here (caller-owned) and soft-skip unreachable /
  // engine-missing ones — never process.exit during an update.
  const catalogs: ModuleCatalog[] = [];
  for (const module of targetModules) {
    const catalog = await resolveModuleCatalog(registry, module, engineId);
    if (!catalog.reachable) {
      logWarn('update:bootstrap', `skipping ${module.id} rules: registry chain unreachable`);
      continue;
    }
    if (!catalog.engineAvailable) {
      logWarn('update:bootstrap', `skipping ${module.id} rules: engine "${engineId}" unavailable`);
      continue;
    }
    catalogs.push(catalog);
  }
  if (catalogs.length === 0) {
    return;
  }

  const { report } = await bootstrapModuleRules(projectDir, config, registry, engineId, catalogs);
  const installed = report.filter(l => l.status === 'installed');
  if (installed.length > 0) {
    const moduleIds = [...new Set(installed.map(l => l.module))].join(', ');
    console.log(chalk.green(`✓ Bootstrapped ${installed.length} rule(s) for newly installed module(s): ${moduleIds}`));
  }
}

export async function updateCommand(options: UpdateCommandOptions = {}): Promise<void> {
  const projectDir = process.cwd();
  const force = Boolean(options.force);
  const installNew = Boolean(options.installNew);
  const skipNew = Boolean(options.skipNew);

  console.log(chalk.bold.blue('\n🎮 UniKit — Update\n'));

  let config = await loadConfig(projectDir);

  if (!config) {
    console.log(chalk.red('Error: No .unikit.json found.'));
    console.log(chalk.dim('Run "unikit-ai init" to set up your project first.'));
    process.exit(1);
  }

  const currentVersion = getCurrentVersion();
  const engineId = config.engine;

  console.log(chalk.dim(`Config version: ${config.version}`));
  console.log(chalk.dim(`Package version: ${currentVersion}`));
  console.log(chalk.dim(`Engine: ${engineId}\n`));

  if (force) {
    console.log(chalk.yellow('⚠ Force mode enabled: clean reinstall of installed skills\n'));
  }

  try {
    // Migrate the on-disk `.unikit/` layout BEFORE anything reads it. The chain
    // relocates the legacy flat `.unikit/memory/{core,stack}` under `code/` AND
    // the flat project workspace (plans/patches/researches + PLAN/FIX_PLAN docs)
    // under `.unikit/code/`, so the skill reinstall and (later) `syncAllModules`
    // Phase 1 reconciliation both operate on the modular layout. Idempotent: a
    // no-op once already migrated. Runs before the `config.version` stamp below.
    const projectVersion = await readConfigVersion(projectDir);
    logInfo('update', `running project migrations (currentVersion=${projectVersion ?? 'null'})`);
    const migrated = await runProjectMemoryMigrations(projectDir, projectVersion);
    logInfo('update', migrated.applied.length > 0
      ? `applied: [${migrated.applied.join(', ')}]`
      : 'no pending migrations');

    // Re-read the config: from Phase 1 on the chain rewrites `.unikit.json`
    // itself (the MCP steps convert `mcp.servers` and rename its keys), so the
    // object loaded above is a snapshot of the PRE-migration file. Every
    // consumer below — `resolveSelectedEngineServer`, the engine-MCP tree
    // delivery, the settings reconciliation — must see the migrated form.
    //
    // This is the same class of ordering bug as the `swapMcpRecheckNotes` call
    // order (read the previous selection BEFORE persisting the new one): a step
    // reading an in-memory copy of a file another step has already rewritten.
    // Re-reading (rather than hoisting the chain above `loadConfig`) keeps the
    // "no config → exit 1" guard and the version banner on the values that were
    // actually on disk when the command started.
    config = (await loadConfig(projectDir)) ?? config;
    logInfo('update', 'config re-read after migrations');

    // Recompute the vendor codes BEFORE anything reads them.
    //
    // `update` never re-asks for servers, so the codes it finds on disk are
    // whatever the last write left there — and after the `mcp-servers-map`
    // migration that is deliberately the OLD code (`UnityMCP`), preserved so the
    // reconciliation can recognise the orphan entry it has to remove. Every
    // artifact below then substitutes `config.engineMcpKey` into itself:
    // `updateSkills`, `updateSubagents`, `installDevPrinciples` and both
    // `build*State` calls. `saveConfig` is the LAST call in the command and does
    // not touch this field, so without a recompute here the stale code is what
    // lands in every installed skill.
    //
    // That failure does not heal on the next run. `mcpHashComponent` is computed
    // from the same stale value, so the following `update` sees no divergence
    // and reinstalls nothing: the prose says `UnityMCP`, `.mcp.json` says
    // `unity-biome-mcp`, the class-B probe finds no key, and the pipeline
    // decides the engine MCP is not configured — silently skipping the
    // compilation and test gates for every run after this one.
    //
    // Same ordering trap as `swapMcpRecheckNotes`: recomputing after the skill
    // loop fixes only the *next* run, recomputing before the config is read
    // has nothing to read.
    const discoveredServers = await discoverMcpServers(engineId);

    // The codes as they were persisted, kept before the map is rewritten. Exactly
    // one consumer needs them — the orphan removal in `reconcileMcpSettings`,
    // which compares "what we registered last time" against "what we register
    // now". After the loop below that information exists nowhere else.
    const storedMcpCodes: Record<string, string> = { ...config.mcp.servers };

    for (const [key, storedCode] of Object.entries(storedMcpCodes)) {
      const server = discoveredServers.get(key);
      // A selection can outlive the file that produced it (a vendor dropped, an
      // engine switched). Leave the entry alone: dropping it here would erase a
      // selection the user may still restore by switching back.
      if (!server) continue;
      if (server.code === storedCode) {
        logInfo('update', `mcp code unchanged: key=${key} code=${storedCode}`);
        continue;
      }
      config.mcp.servers[key] = server.code;
      logInfo('update', `mcp code rewritten: key=${key} ${storedCode} -> ${server.code}`);
    }

    const selectedEngineServer = resolveSelectedEngineServer(discoveredServers, Object.keys(config.mcp.servers));
    const recomputedEngineCode = selectedEngineServer?.entry.code ?? null;
    if (recomputedEngineCode !== config.engineMcpKey) {
      logInfo('update', `engineMcpKey recomputed: ${config.engineMcpKey ?? 'null'} -> ${recomputedEngineCode ?? 'null'}`);
      config.engineMcpKey = recomputedEngineCode;
    } else {
      logInfo('update', `engineMcpKey unchanged: ${config.engineMcpKey ?? 'null'}`);
    }

    // Refresh extensions from sources (check for updates)
    let extensions = config.extensions ?? [];
    if (extensions.length > 0) {
      console.log(chalk.dim('Checking extensions for updates...\n'));
      const extRefresh = await refreshExtensions(projectDir, config, { force });
      if (extRefresh.updated.length > 0) {
        console.log(chalk.green(`✓ Extensions updated: ${extRefresh.updated.join(', ')}`));
      }
      if (extRefresh.failed.length > 0) {
        console.log(chalk.yellow(`⚠ Extension update failed: ${extRefresh.failed.join(', ')}`));
      }
      await saveConfig(projectDir, config);
      // Re-read extensions after refresh (commitResolvedExtension replaces config.extensions)
      extensions = config.extensions ?? [];
    }

    // Collect replaced skills from extensions
    const replacedSkills = collectReplacedSkills(config.extensions ?? []);

    // Snapshot the skills newly added to the package BEFORE the update loop
    // mutates agent.installedSkills below. A skill is "new" when the package
    // ships it but it is installed for NO agent yet (union across all agents).
    const packageSkills = await getAvailableSkills();
    const installedUnion = new Set(config.agents.flatMap(a => a.installedSkills));
    const newSkills = packageSkills.filter(s => !installedUnion.has(s));

    // Resolve the opt-in install set for new skills. Lifted to function scope so
    // the rules-bootstrap step (after createRegistry below) can target the
    // modules these new skills belong to. Conflict policy: --skip-new wins over
    // --install-new (never install silently when the user asked to skip). With
    // neither flag, prompt only on a TTY; non-TTY stays a no-op (CI-safe
    // back-compat). Empty newSkills short-circuits to a no-op without rendering
    // an empty checkbox prompt.
    const installNewSkills = new Set<string>();
    if (!skipNew && newSkills.length > 0) {
      if (installNew) {
        for (const skill of newSkills) installNewSkills.add(skill);
      } else if (process.stdout.isTTY) {
        // Lazy: `inquirer` is ~240ms of module graph and this is the only branch
        // in the whole command that needs it. Every non-TTY run (the entire test
        // suite, and CI) used to pay for it at import time.
        const { default: inquirer } = await import('inquirer');
        const { chosen } = await inquirer.prompt([
          {
            type: 'checkbox',
            name: 'chosen',
            message: 'New skills are available in this package version. Deselect any you do not want, then confirm:',
            // Default CHECKED: new skills are opt-out. The common case after an
            // update is "give me the new stuff", so pressing Enter installs all
            // of them; uncheck the ones you deliberately want to skip.
            choices: newSkills.map(skill => ({ name: skill, value: skill, checked: true })),
          },
        ]);
        for (const skill of chosen as string[]) installNewSkills.add(skill);
      }
    }

    // Update skills per agent
    console.log(chalk.dim('Updating skills...\n'));

    const entriesByAgent = new Map<string, SkillUpdateEntry[]>();

    for (const agent of config.agents) {
      const result = await updateSkills(agent, projectDir, { force, engineId, engineMcpKey: config.engineMcpKey, mcpServers: config.mcp.servers, replacedSkills, installNewSkills });
      agent.installedSkills = result.installedSkills;
      entriesByAgent.set(agent.id, result.entries);
    }

    // Install/refresh engine templates
    await installEngineTemplates(projectDir, engineId, config.agents);

    // Update subagents per agent
    console.log(chalk.dim('Updating subagents...\n'));

    const subagentEntriesByAgent = new Map<string, SubagentUpdateEntry[]>();

    for (const agent of config.agents) {
      const agentCfg = getAgentConfig(agent.id);
      if (agentCfg.supportsSubagents) {
        const result = await updateSubagents(agent, projectDir, { force, engineId, engineMcpKey: config.engineMcpKey, mcpServers: config.mcp.servers });
        agent.installedSubagents = result.installedSubagents;
        subagentEntriesByAgent.set(agent.id, result.entries);
      }
    }

    // Reinstall extension skills and subagents (recover if missing after base updates)
    if (extensions.length > 0) {
      for (const ext of extensions) {
        const extManifest = await loadExtensionManifest(getExtensionDir(projectDir, ext.name));
        if (!extManifest) continue;

        const extensionDir = getExtensionDir(projectDir, ext.name);
        for (const agent of config.agents) {
          if (extManifest.skills?.length) {
            await installExtensionSkills(projectDir, agent, extensionDir, extManifest.skills, engineId, config.engineMcpKey);
          }
          if (extManifest.subagents?.length) {
            await installExtensionSubagents(projectDir, agent, extensionDir, extManifest.subagents, engineId, config.engineMcpKey);
          }
        }
      }
    }

    // Inject MCP tool permissions (after all skills — base + extension — are installed)
    console.log(chalk.dim('Injecting MCP tool permissions...\n'));
    const mcpAllowedTools = collectMcpRules(discoveredServers, Object.keys(config.mcp.servers));
    await injectMcpRules(projectDir, config.agents, mcpAllowedTools);

    // Re-apply extension injections (after base skills updated + MCP injected)
    if (extensions.length > 0) {
      console.log(chalk.dim('Re-applying extension injections...\n'));

      for (const ext of extensions) {
        const extManifest = await loadExtensionManifest(getExtensionDir(projectDir, ext.name));
        if (!extManifest?.injections?.length) continue;

        const extensionDir = getExtensionDir(projectDir, ext.name);
        for (const agent of config.agents) {
          await applyAllInjections(projectDir, agent, ext.name, extManifest.injections, extensionDir);
        }
      }
    }

    // Sync rules (shared) — single call into syncAllModules runs each module's
    // Phase 1-3 (disk↔state reconciliation, registry sync, RULES_INDEX.md regen).
    // `update --force` propagates as `{ replace: true, prune: true }` — the
    // exact composition that used to be called `sync --force`: overwrite local
    // modifications AND remove obsolete stack rules. Normal `update` (no
    // `--force`) maps to `{ replace: false, prune: false }` and behaves like
    // the lean `rules sync`.
    console.log(chalk.dim('Syncing rules...\n'));

    const registry = createRegistry(config.rulesRegistry, engineId);

    // Bootstrap rules for modules whose FIRST skill was installed this run
    // (close the gap: opting into a module's skills via update must deliver its
    // rules — Phase 2 sync only carries already-installed rules). Runs BEFORE
    // syncAllModules so Phase 1 keeps them (source:registry), Phase 2 skips them
    // (version equal), and Phase 3 regenerates the index including them.
    await bootstrapNewSkillModuleRules(projectDir, config, registry, engineId, installNewSkills);

    const syncResult = await syncAllModules(projectDir, engineId, config, registry, {
      replace: force,
      prune: force,
    });
    renderSyncRulesEvents(syncResult.events);

    // Update CLI contract
    await installCliContract(projectDir);

    // Refresh machine-readable gate-result contract (read by verify + review)
    await installGateResultContract(projectDir);

    // `update` does not re-ask for servers, but the selection still moves under
    // it: editing `.unikit.json` and re-running is how an engine switch reaches
    // this command, and everything else here already honours it (skills are
    // reinstalled, stale grants cleared, the rules tree swept). The findings log
    // has to follow the same switch, or a note about the old server stays active
    // under the new one and reads as evidence about it.
    //
    // The previous id comes from the stamp in the tree currently on disk — the
    // only before-state this command has, since the config is already the new
    // answer. Read it BEFORE installEngineMcpRules overwrites the stamp.
    const previousEngineServer = await readDeliveredEngineMcpServer(projectDir);
    await swapMcpRecheckNotes(projectDir, previousEngineServer, selectedEngineServer?.fileId ?? null);

    // Refresh the selected server's rules tree (orphan-deletes a stale engine's copy)
    await installEngineMcpRules(projectDir, selectedEngineServer);

    // Update engine development principles (shared system file, plain rewrite)
    await installDevPrinciples(projectDir, engineId, config.engineMcpKey);

    // Refresh module registry snapshot (flat rewrite, forward-compat SSOT)
    await installModulesYml(projectDir);

    // Refresh game-design system assets — gd-principles core + shards +
    // shared design-read contract (engine-agnostic flat rewrites under gamedesign/);
    // also orphan-deletes the pre-split flat .unikit/system/gd-principles.md
    await installGamedesignSystemAssets(projectDir);

    // Refresh selectively installed genre profiles (flat rewrite of state set)
    await installGenreProfiles(projectDir, config);

    // Rebuild managed state per agent (exclude replaced skills)
    const availableSkills = await getAvailableSkills();
    for (const agent of config.agents) {
      const managedSkills = agent.installedSkills.filter(s => availableSkills.includes(s) && !replacedSkills.has(s));
      agent.managedSkills = await buildManagedSkillsState(projectDir, agent, managedSkills, engineId, config.engineMcpKey, config.mcp.servers);
      agent.managedSubagents = await buildManagedSubagentsState(projectDir, agent, agent.installedSubagents, engineId, config.engineMcpKey, config.mcp.servers);
    }

    config.version = currentVersion;
    await saveConfig(projectDir, config);

    console.log(chalk.green('✓ Skills updated'));
    console.log(chalk.green('✓ Subagents updated'));
    console.log(chalk.green('✓ Configuration saved'));

    // Per-agent status
    for (const agent of config.agents) {
      const entries = entriesByAgent.get(agent.id) ?? [];
      const grouped = groupEntriesByStatus(entries);
      const changedWithContextWarnings: string[] = [];

      for (const entry of grouped.changed) {
        const skillContextPath = path.join(projectDir, '.unikit', 'skill-context', entry.skill, 'SKILL.md');
        if (await fileExists(skillContextPath)) {
          changedWithContextWarnings.push(entry.skill);
        }
      }

      console.log(chalk.bold(`\n[${agent.id}] Skills status:`));
      console.log(chalk.dim(`  changed: ${grouped.changed.length}`));
      console.log(chalk.dim(`  unchanged: ${grouped.unchanged.length}`));
      console.log(chalk.dim(`  skipped: ${grouped.skipped.length}`));
      console.log(chalk.dim(`  removed: ${grouped.removed.length}`));

      if (grouped.changed.length > 0) {
        console.log(chalk.bold('  Changed:'));
        for (const entry of grouped.changed) {
          console.log(chalk.dim(`    - ${entry.skill} (${formatReason(entry.reason)})`));
        }
      }

      if (grouped.skipped.length > 0) {
        console.log(chalk.bold('  Skipped:'));
        for (const entry of grouped.skipped) {
          console.log(chalk.dim(`    - ${entry.skill} (${formatReason(entry.reason)})`));
        }
      }

      if (grouped.removed.length > 0) {
        console.log(chalk.bold('  Removed:'));
        for (const entry of grouped.removed) {
          console.log(chalk.dim(`    - ${entry.skill} (${formatReason(entry.reason)})`));
        }
      }

      const recoveryEntries = grouped.changed.filter(entry => [
        'missing-managed-state',
        'missing-installed-artifact',
        'source-missing',
      ].includes(entry.reason));
      if (recoveryEntries.length > 0) {
        console.log(chalk.yellow('  WARN: managed state recovered for:'));
        for (const entry of recoveryEntries) {
          console.log(chalk.yellow(`    - ${entry.skill} (${formatReason(entry.reason)})`));
        }
      }

      if (changedWithContextWarnings.length > 0) {
        console.log(chalk.yellow('  WARN: skill-context override may need review for changed skills:'));
        for (const skill of changedWithContextWarnings) {
          console.log(chalk.yellow(`    - ${skill} (.unikit/skill-context/${skill}/SKILL.md)`));
        }
      }
    }

    // Rules summary — syncAllModules already printed per-event detail via
    // renderSyncRulesEvents; here we just emit a one-line status marker.
    const rulesUpdated = syncResult.events.filter(e =>
      e.kind === 'phase2:updating' || e.kind === 'phase1:untracked-found' ||
      e.kind === 'phase1:missing-removed' || e.kind === 'phase2:obsolete-removed',
    ).length;

    if (syncResult.changed) {
      console.log(chalk.green(`\n✓ Rules synced (${rulesUpdated} change${rulesUpdated === 1 ? '' : 's'})`));
    } else {
      console.log(chalk.green('\n✓ Rules up to date'));
    }

    console.log('');

  } catch (error) {
    console.log(chalk.red(`Error updating: ${(error as Error).message}`));
    process.exit(1);
  }
}
