import chalk from 'chalk';
import type { UniKitConfig } from '../../core/config.js';
import type { SkillUpdateEntry } from '../../core/installer/skills.js';
import type { ChainedRegistry } from '../../core/registry/index.js';
import { bootstrapModuleRules } from '../../core/installer/rules-bootstrap.js';
import { resolveModuleCatalog, type ModuleCatalog } from '../../core/installer/module-catalog.js';
import { listModules, resolveSkillModule, moduleHasInstalledSkills } from '../../core/modules.js';
import { logWarn } from '../../utils/log.js';

// Helpers of the `update` command, kept out of update.ts so the command itself stays under the
// 500-line ceiling (guarded by Part 7i): how a skill-update reason is worded, how the entries
// are grouped for the report, and the rules bootstrap for a module that just got its first skill.

export function formatReason(reason: string): string {
  switch (reason) {
    case 'source-hash-changed':
      return 'source changed';
    case 'installed-hash-drift':
      return 'local drift';
    case 'missing-managed-state':
      return 'state missing';
    case 'missing-installed-artifact':
      return 'artifact missing';
    case 'package-removed':
      return 'removed from package';
    case 'new-skill-not-installed':
      return 'new in package';
    case 'new-skill-installed':
      return 'new skill installed';
    case 'force-clean-reinstall':
      return 'force reinstall';
    case 'install-failed':
      return 'install failed';
    case 'source-missing':
      return 'source unavailable';
    case 'replaced-by-extension':
      return 'replaced by extension';
    default:
      return reason;
  }
}

export function groupEntriesByStatus(entries: SkillUpdateEntry[]): Record<'changed' | 'unchanged' | 'skipped' | 'removed' | 'replaced', SkillUpdateEntry[]> {
  return {
    changed: entries.filter(entry => entry.status === 'changed').sort((a, b) => a.skill.localeCompare(b.skill)),
    unchanged: entries.filter(entry => entry.status === 'unchanged').sort((a, b) => a.skill.localeCompare(b.skill)),
    skipped: entries.filter(entry => entry.status === 'skipped').sort((a, b) => a.skill.localeCompare(b.skill)),
    removed: entries.filter(entry => entry.status === 'removed').sort((a, b) => a.skill.localeCompare(b.skill)),
    replaced: entries.filter(entry => entry.status === 'replaced').sort((a, b) => a.skill.localeCompare(b.skill)),
  };
}

/**
 * Bootstrap rules for modules that received their FIRST skill in this update run
 * (`update --install-new` / the interactive new-skill prompt). The invariant is
 * bootstrap = f(installed skills): a project that just opted into a new module's
 * skills must also receive that module's rules, which the Phase 2 sync that
 * follows cannot deliver (it only carries already-installed rules).
 *
 * EXIT-FREE: catalogs are resolved here and unreachable / engine-missing ones
 * are soft-skipped (a flaky or code-only registry must not abort the update).
 * config mutations are persisted by updateCommand's own saveConfig and the
 * index is regenerated by syncAllModules Phase 3 — neither happens here.
 */
export async function bootstrapNewSkillModuleRules(
  projectDir: string,
  config: UniKitConfig,
  registry: ChainedRegistry,
  engineId: string,
  installNewSkills: Set<string>,
): Promise<void> {
  if (installNewSkills.size === 0) {
    return;
  }

  const newSkillList = [...installNewSkills];
  const targetModules = listModules().filter(module =>
    newSkillList.some(s => resolveSkillModule(s)?.id === module.id)
    && moduleHasInstalledSkills(config, module),
  );
  if (targetModules.length === 0) {
    return;
  }

  // Resolve catalogs here (caller-owned) and soft-skip unreachable /
  // engine-missing ones — never process.exit during an update.
  const catalogs: ModuleCatalog[] = [];
  for (const module of targetModules) {
    const catalog = await resolveModuleCatalog(registry, module, engineId);
    if (!catalog.reachable) {
      logWarn('update:bootstrap', `skipping ${module.id} rules: registry chain unreachable`);
      continue;
    }
    if (!catalog.engineAvailable) {
      logWarn('update:bootstrap', `skipping ${module.id} rules: engine "${engineId}" unavailable`);
      continue;
    }
    catalogs.push(catalog);
  }
  if (catalogs.length === 0) {
    return;
  }

  const { report } = await bootstrapModuleRules(projectDir, config, registry, engineId, catalogs);
  const installed = report.filter(l => l.status === 'installed');
  if (installed.length > 0) {
    const moduleIds = [...new Set(installed.map(l => l.module))].join(', ');
    console.log(chalk.green(`✓ Bootstrapped ${installed.length} rule(s) for newly installed module(s): ${moduleIds}`));
  }
}
